server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: gatewayroute
          url: http://localhost:9001
          predicates:
            - Path =/gate/**,/rule/**
          filters:
            - PrefixPath= /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:800/eurka
  instance:
    prefer-ip-address: true
