server:
  port: 9000

spring:
  application:
    name: mallgateway
  cloud:
    gateway:
      routes:
#        - id: gatewayroute
          url: http://localhost:9001
          predicates:
            - Path =/gate/**,/rule/**
          filters:
            - PrefixPath= /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: mallgateway
