package com.mall.ordercenter.dao;

import com.mall.ordercenter.domain.ChardancemallOrderGoods;
import com.mall.ordercenter.domain.ChardancemallOrderGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChardancemallOrderGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    long countByExample(ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int deleteByExample(ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int insert(ChardancemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int insertSelective(ChardancemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    ChardancemallOrderGoods selectOneByExample(ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    ChardancemallOrderGoods selectOneByExampleSelective(@Param("example") ChardancemallOrderGoodsExample example, @Param("selective") ChardancemallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    List<ChardancemallOrderGoods> selectByExampleSelective(@Param("example") ChardancemallOrderGoodsExample example, @Param("selective") ChardancemallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    List<ChardancemallOrderGoods> selectByExample(ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    ChardancemallOrderGoods selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ChardancemallOrderGoods.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    ChardancemallOrderGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    ChardancemallOrderGoods selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ChardancemallOrderGoods record, @Param("example") ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ChardancemallOrderGoods record, @Param("example") ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ChardancemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ChardancemallOrderGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") ChardancemallOrderGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chardancemall_order_goods
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}